#!/bin/bash

# clean-for-client.sh - Removes AI tool traces and development artifacts from code

echo "🧹 Cleaning repository for client viewing..."

# Remove .cursor directory and files
if [ -d ".cursor" ]; then
    echo "- Removing .cursor directory"
    rm -rf .cursor
fi

# Remove any context7.json files
find . -name "context7.json" -type f -delete
echo "- Removed context7.json files"

# Remove Claude markers and Cursor artifacts
find . -type f -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" -o -name "*.css" -o -name "*.html" | while read file; do
    # Skip node_modules
    if [[ $file == *"node_modules"* ]]; then
        continue
    fi

    # Remove AI prompts, cursor comments, and developer notes
    sed -i '/\/\/ NOTE: This code was generated/d' "$file"
    sed -i '/\/\/ Generated by/d' "$file"
    sed -i '/\/\/ Claude:/d' "$file"
    sed -i '/\/\/ Cursor:/d' "$file"
    sed -i '/\/\/ TODO:/d' "$file"
    sed -i '/\/\/ FIXME:/d' "$file"
    sed -i '/\/\/ DEV:/d' "$file"

    # Remove empty comment blocks
    sed -i '/\/\*\s*\*\//d' "$file"
done

echo "- Cleaned code comments from source files"

# Remove development-only files
REMOVE_LIST=(
    ".env.local"
    ".env.development"
    ".env.test"
    "NOTES.md"
    "DEV_NOTES.md"
    "TODO.md"
    "ROADMAP.md"
    ".vscode"
)

for item in "${REMOVE_LIST[@]}"; do
    if [ -e "$item" ]; then
        echo "- Removing $item"
        rm -rf "$item"
    fi
done

# Remove sensitive environment files but keep a sample
if [ -f ".env" ]; then
    echo "- Creating sanitized .env.example from .env"
    grep -v "SECRET\|KEY\|PASSWORD\|TOKEN" .env | sed 's/=.*/=YOUR_VALUE_HERE/g' >.env.example
    echo "- Removing .env"
    rm .env
fi

# Clean up README.md if it contains development notes
if [ -f "README.md" ]; then
    # Remove sections marked for development only
    sed -i '/<!-- DEV ONLY/,/DEV ONLY -->/d' "README.md"
    sed -i '/## Development Notes/,/## /d' "README.md"
    sed -i '/## TODO/,/## /d' "README.md"
    echo "- Cleaned README.md"
fi

echo "✅ Repository cleaned successfully for client viewing!"
